masters = gentoo

manifest-hashes = BLAKE2B SHA512
manifest-required-hashes = BLAKE2B
update-changelog = false
cache-formats = md5-dict
thin-manifests = true
sign-manifests = false

# Current Rust and systemd eclasses in ::gentoo support EAPI 8.
eapis-banned = 0 1 2 3 4 5 6 7
